---

- name: Unarchive cfg2html source archive
  ansible.builtin.unarchive:
    src: "{{ cfg2html_source_archive }}"
    dest: "{{ cfg2html_root | dirname }}"
    remote_src: yes

- name: Create symlink to latest version
  ansible.builtin.command:
    cmd: ln -fs cfg2html-{{ cfg2html_version }} cfg2html
  args:
    chdir: "{{ cfg2html_root | dirname }}"
  changed_when: no
